### ISSUE TITLE
Change repo name

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/popupCycleways#17]
I suggest to popupCycleways

Any objections or other suggestions?

**Comment by jf1** [comment]
+1 from me as it's definitely an improvement, however for your longer-term consideration, and as these projects have so far favoured acronyms...

S	Safe
T	Transport
O	Options
I	In
C	Covid/COVID-19
(E)	Environments

Which would enable eg STOIC(E)-Cycleways and STOIC(E)-Footways repositories (I'm presuming you could also identify spare width rather than just lanes, by using OS data under a Covid license). I like the idea that the name of the repository encourages LAs to do the right thing from a moral perspective, but am aware others here may have a better understanding of this aspect and its relevance / suitability.

**Comment by mvl22** [comment]
popupCycleways has the benefit of being self-explanatory, unlike virtually every other academic project name involving acronyms I have ever come across...
