### ISSUE TITLE
Manchester analysis

### ISSUE THREAD

**Issue by Robinlovelace** [cyipt/popupCycleways#27]

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/82181124-d65d8600-98d9-11ea-8835-98647333ffe2.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/82181197-f5f4ae80-98d9-11ea-8b8e-52a5c7ef59f5.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/82247178-dd1de480-993d-11ea-8375-4e8831761122.png)


Finding: best to group by ref, more consistent.

**Comment by Robinlovelace** [comment]
With spare lanes showing

![image](https://user-images.githubusercontent.com/1825120/82248936-de9cdc00-9940-11ea-918c-f6351548ae68.png)

**Comment by Robinlovelace** [comment]
![mcr-census-results](https://user-images.githubusercontent.com/1825120/82254618-10b33b80-994b-11ea-85ef-5edee3a53ac5.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/82258452-caada600-9951-11ea-8af0-520c8407928a.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/82259634-d732fe00-9953-11ea-94bf-60b5dfe65f36.png)

**Comment by jf1** [comment]
Thanks @Robinlovelace - these look good :smile: however I would suggest / request the following if practical...

A6 labelled as NW and SE, or N and S if you're only considering the 4 primary compass points.

Shorten some of the lines in your [penultimate post](https://github.com/cyipt/popupCycleways/issues/27#issuecomment-630428765) as they extend well beyond areas I'd consider built up / high value. I'd trim five of them as per the solid pink lines below, and would also consider trimming the A57 E at the dotted pink line.

![GM-household-motor-access-cyipt-popupcycleways](https://user-images.githubusercontent.com/4711363/82567136-ddec8b80-9b74-11ea-829b-5d997251b593.jpg)

Edge Lane / Wilbraham Road featured in previous releases and is still visible [here](https://cyipt.github.io/popupCycleways/manchester.html). It's a very high value route - some is already coned and was featured on Tuesday's BBCNW news. It doesn't connect to the regional centre but I'd welcome its return. I've added a green line for the most obvious section. I reckon another ~500m at each end would be practical and useful - I'd be interested to if the algorithm agrees, even if the grouping system needs some help to continue along roads with different names or numbers.

I've also added green lines for Leigh, Wigan, Bolton, Middleton / Heywood / Rochdale, and Ashton-under-Lyne. Might these show up in a top 15 rather than top 10, or are you able to detail what parameters these routes have or don't have that results in them not being included?

For info the basemap shows no vehicle in household which I find useful to highlight both the built up area and also the likely demand for non-car transport.

**Comment by Robinlovelace** [comment]
Hi @jf1 thanks for the very useful feedback. The mini project that this was for is now complete, so closing for now. My work was largely guided by Brian Deegan on behalf of Chris Boardman and others involved in high-level plans Greater Manchester. I should say I think your suggestions are sensible and I would like to do them, it's just a question of time now that the priority is generating results nationwide which is a much harder job. The good news is that the experience of doing the work on Manchester has informed our approach leading to refinements in the methods, which are implemented in the `build.R` script, which I'm sorry to say, is probably rather difficult to decipher for people who are not relatively experienced with R.

**Comment by Robinlovelace** [comment]
The latest results from this work can be seen here: https://github.com/cyipt/popupCycleways/blob/master/code/mcr-safe-streets-analysis.md#analysis-of-cycling-potential-around-key-corridors-in-greater-manchester

**Comment by jf1** [comment]
Thanks for the reply @Robinlovelace and in case it wasn't clear my feedback was mostly intended to help you produce better nationwide results - the GM decisions had been made before I posted that reply.

ps. We now have cones on both sides of the A56 :smile: [tfgm traffic-cameras/chester-rd-davyhulme-rd](https://tfgm.com/roads/live-traffic-cameras/chester-rd-davyhulme-rd)
Here's the first side going in:![image](https://user-images.githubusercontent.com/4711363/82913110-cdb62100-9f65-11ea-9ae0-6f94aad8ea03.png)

**Comment by Robinlovelace** [comment]
Amazing!

**Comment by Robinlovelace** [comment]
Heads-up @jf1 we have new results for Manchester, please can you take a look and let us know your thoughts: https://cyipt.github.io/popupCycleways/v0.1/greater%20manchester/m

Known issue, some of the roads are too long and drift off into the countryside. See #42

**Comment by mvl22** [comment]
I would recommend avoiding keys with a space in the name, i.e. "greater manchester" as these result in URLs that are liable to break during circulation.

**Comment by Robinlovelace** [comment]
Agreed @mvl22, I suggest `greater-manchester`. Any other suggestions?

**Comment by jf1** [comment]
Thanks @Robinlovelace - although I'm not sure what type of feedback you're after so you or colleagues are welcome to clarify if there's anything specific.

Does a `Top route` have spare lanes and high potential, or is just about the potential?

Is `Missing` for missing links? (and if so please could it be bright pink / magenta!)
I note you show Stretford's Kingsway like this - something I've identified in the Trafford network map at the end of this post. All but 2 of the items on my map are either already usable or well worth upgrading, so any alignment between outputs is welcome.

FYI B5158 has a cycleway on it so shouldn't be 'missing' - it's part of the `Flixton-Carrington N-S` link on my map that ideally would be longer on yours. I note you're missing the Birch Road section (a private road that's currently used as a bridleway and will soon be recorded on the definitive map).

Another missing pedestrian section is School Road, Sale - ideally you'd match what we do at this location:
![image](https://user-images.githubusercontent.com/4711363/83012427-4d4df980-a013-11ea-90e7-4b0b39fafd41.png)

And a missing spare lanes link (that's short but crucial as it goes over a train line):
![image](https://user-images.githubusercontent.com/4711363/83014208-3361e600-a016-11ea-9adb-e9d26d798166.png)

For @mvl22's info, this is part of the old A56 that I've mentioned before as cycle routing engines discourage use but it's one of the most spacious and lower traffic options, that sadly still has A-road designation but ideally would feature more in route recommendations. It's a calm environment, and I'm not the only person who prefers it over the new protected infrastructure on the noisy/polluted Stretford Road.

A strange result in Manchester - the `A5067 Chorlton Road width 6.00` is described as 'missing' yet it is only half of a dual carriageway so mcc could cone off a lane or build a decent cycleway if they wanted to (although this 'flagship route' is currently having 1.5m terraced tracks installed :disappointed:). Just for my curiosity, please can you confirm how its potential ranks compared to the rest of GM?

![Trafford-base-network-20200526-hd](https://user-images.githubusercontent.com/4711363/83012256-10820280-a013-11ea-9c1c-d0a2c783286f.png)
